### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by jakeva** [AlexProgrammerDE/balena-minecraft-bungeecord#1]
Hello!

I wanted to bring up the idea to update the documentation for this project to show a step-by-step solution to creating one's own "bungeecord network" hosted directly from the raspberry pi using balenaCloud's services.

I believe the documentation should replicate this format:
https://www.balena.io/blog/how-to-create-a-minecraft-server-for-the-pi-4-with-balena/

**Comment by AlexProgrammerDE** [comment]
@JakeValenzuela so you are planning to host a whole minecraft network on multiple raspberry pis?

**Comment by jakeva** [comment]
I wanted to host the entire network on a single raspberry pi. This is only for developmental purposes as well, so performance isn't a concern.

**Comment by AlexProgrammerDE** [comment]
@JakeValenzuela i think this would cause some giant performance problems. A single Server isn't very fast. Multiple servers could cause some serious prformance problems. If you really just want to run two servers and a bungeecord proxy take a look at this blog post: https://www.balena.io/blog/two-projects-one-device-turn-your-raspberry-pi-into-a-multitool/ It explains how to use multiple projects at the same time.
